### PR TITLE
Develop --> Master PR for Redmi/Image Uploads

### PR DESCRIPTION
**Pull request by celanthe**
Develop --> Master PR for DevRel 48 image additions and Redmi information

### CODE REVIEW

**Review by kzotter — CHANGES_REQUESTED** [review]
Change this:
If you are provisioning a Redmi device, you will need to perform the steps mentioned below in order to access the device provisioner:

To:
If you are provisioning a Redmi device, you will need to perform the steps mentioned below and then use the Esper Device Provisioner to enroll your device into Esper:

**Comment by celanthe** [comment]
> Change this:
> If you are provisioning a Redmi device, you will need to perform the steps mentioned below in order to access the device provisioner:
> 
> To:
> If you are provisioning a Redmi device, you will need to perform the steps mentioned below and then use the Esper Device Provisioner to enroll your device into Esper:

Done!

**Review by celanthe — COMMENTED** [review]
Made this change!

**Review by kzotter — APPROVED** [review]

**Comment by celanthe** [comment]
@kirananto @VineethaVR are either of you able to merge this by any chance? Thank you so much!

**Comment by kirananto** [comment]
Unable to merge because of deploy failure caused by Certain images missing

1. ManageDevicesCSV.png
2. ContactsIncomingCalls.png

**Pull request merged**
